---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Filebeat is installed
  ansible.builtin.package:
    name: filebeat
    state: present
